# Generated by Django 5.2.12 on 2026-08-16 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=30, unique=True)),
                ('size', models.CharField(max_length=30)),
                ('units_per_case', models.PositiveIntegerField()),
                ('case_weight_kg', models.DecimalField(decimal_places=3, max_digits=8)),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='territory',
            name='high_freight_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='territory',
            name='low_freight_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='territory',
            name='medium_freight_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('customer_type', models.CharField(choices=[('WHOLESALER', 'Wholesaler'), ('RETAILER', 'Retailer')], max_length=20)),
                ('payment_status', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributors', to='orders.territory')),
            ],
        ),
    ]
