# Generated by Django 5.2.12 on 2026-08-16 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_driver_truck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='truck_code',
        ),
    ]
