# Generated by Django 5.2.12 on 2026-08-17 03:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(blank=True, max_length=150)),
                ('receiver_id', models.CharField(blank=True, max_length=50)),
                ('receiver_phone', models.CharField(blank=True, max_length=30)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_number', models.CharField(max_length=40, unique=True)),
                ('external_driver_name', models.CharField(blank=True, max_length=150)),
                ('external_truck_plate', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DispatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='package_type',
            field=models.CharField(blank=True, choices=[('PET', 'PET'), ('CAN', 'Can')], max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='distributor',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('territory',), name='one_active_distributor_per_territory'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.driver'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='orders.order'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.truck'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='dispatch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_note', to='orders.dispatch'),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='dispatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.dispatch'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='orders.product'),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_items', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request', to='orders.order'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='unique_product_per_order'),
        ),
        migrations.AddConstraint(
            model_name='dispatchitem',
            constraint=models.UniqueConstraint(fields=('dispatch', 'order_item'), name='unique_item_per_dispatch'),
        ),
    ]
