# Generated by Django 5.2.12 on 2026-08-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_deliverynote_dispatch_dispatchitem_orderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='package_type',
            field=models.CharField(choices=[('PET', 'PET'), ('CAN', 'Can')], max_length=20),
        ),
    ]
