# Generated by Django 5.2.12 on 2026-08-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_product_package_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='dispatch_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
