# Generated by Django 5.2.12 on 2026-08-23 04:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_dispatch_dispatch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='dispatch_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
